Develop copy

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,10 +1,11 @@
 build_config: &build_config
   BUILD_IMAGE_NAME: xnat/node-java-build
   BUILD_IMAGE_TAG: latest
-  CACHE_VERSION: v1
-  NODE_VERSION: "v10.20.1"
+  CACHE_VERSION: v2
+  NODE_VERSION: "v10.22.0"
   NVM_VERSION: "0.35.3"
-  JAVA_VERSION: "zulu8.46.0.19-ca-jdk8.0.252"
+  JAVA_VERSION: "zulu8.48.0.53-ca-jdk8.0.265"
+  JDK_ROOT: "https://cdn.azul.com/zulu/bin"
 
 version: 2
 
@@ -40,17 +41,18 @@ jobs:
       - run:
           name: Build Windows 64-bit executable and installer
           command: |
-              export JAVA_HOME="/opt/java/win-x64"
-              yarn dist-win-x64
+              export JAVA_HOME="${JAVA_HOME_WIN}"
+              echo "Skipping 'yarn dist-win-x64'"
+              #yarn dist-win-x64
       - run:
           name: Build Linux 64-bit executable and installer
           command: |
-              export JAVA_HOME="/opt/java/linux-x64"
+              export JAVA_HOME="${JAVA_HOME_LINUX}"
               yarn dist-linux-x64
       - run:
           name: Copy build artifacts to artifacts folder
           command: |
-            mkdir artifacts
+            [[ ! -d artifacts ]] && { mkdir -p artifacts; }
             find dist -mindepth 1 -maxdepth 1 -type f -print0 | xargs --null -I {} cp {} artifacts
       - run:
           name: Upload artifacts to Bitbucket downloads page when the build is on the master branch
@@ -98,15 +100,37 @@ jobs:
       - restore_cache:
           key: cache-${CACHE_VERSION}-mac-{{ .Branch }}-{{ checksum "package.json" }}
       - run:
+          name: Copy installed JDK to application folder
+          command: |
+            [[ ! -f /Applications/XNAT-Desktop-Client.app/Contents/Resources/jre/lib/jli/libjli.dylib ]] && {
+              [[ -d /Applications/XNAT-Desktop-Client.app ]] && { rm -rf /Applications/XNAT-Desktop-Client.app; }
+              cp -R /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk /Applications/XNAT-Desktop-Client.app
+              cp -R /Applications/XNAT-Desktop-Client.app/Contents/Home /Applications/XNAT-Desktop-Client.app/Contents/Resources
+            }
+      - run:
           name: Download and expand JRE for Mac
           command: |
-            [[ ! -d build_resources/jre/mac ]] && {
-                JAVA_TARGET="${JAVA_VERSION}-macosx_x64"
-                http --download https://cdn.azul.com/zulu/bin/${JAVA_TARGET}.zip
-                unzip ${JAVA_TARGET}.zip
-                mv ${JAVA_TARGET} build_resources/jre/mac
-                rm -rf ${JAVA_TARGET}.zip
+            [[ -d build_resources/jre/mac ]] && {
+                [[ $(find build_resources/jre/mac -mindepth 1 -maxdepth 1 -type d -name bin | wc -l | tr -d ' ') == 0 ||
+                   ! -f build_resources/jre/mac/bin/java ||
+                   $(build_resources/jre/mac/bin/java -version 2>&1 | grep ${JAVA_TOKEN} | wc -l | tr -d ' ') == 0 ]] && {
+                    rm -rf build_resources/jre/mac;
+                 }
             }
+            [[ ! -d build_resources/jre/mac ]] && {
+                [[ -d build_resources/jre/mac ]] && { rm -rf build_resources/jre/mac; }
+                JAVA_TARGET="${JAVA_VERSION}-macosx_x64"
+                echo "No JRE found, downloading ${JAVA_VERSION}"
+                http --download ${JDK_ROOT}/${JAVA_TARGET}.zip
+                unzip ${JAVA_TARGET}.zip
+                mv ${JAVA_TARGET}/zulu-8.jdk/Contents/Home/jre build_resources/jre/mac
+                rm -rf ${JAVA_TARGET}*
+                echo "JRE installed, using version: $(build_resources/jre/mac/bin/java -version 2>&1 | grep Server)"
+            } || {
+                echo "Existing JRE found, using version: $(build_resources/jre/mac/bin/java -version 2>&1 | grep Server)"
+            }
+            # Last, make sure there are no read-only files! These cause the update process to fail.
+            find build_resources/jre/mac -type f -perm +444 ! -perm +222 -exec chmod +w '{}' \;
       - run:
           name: Install and build node dependencies
           command: |
@@ -117,6 +141,7 @@ jobs:
           paths:
             - node_modules
             - build_resources/jre/mac
+            - /Applications/XNAT-Desktop-Client.app
       - run:
           name: Build Mac executable and installer
           command: |
@@ -125,7 +150,7 @@ jobs:
       - run:
           name: Copy build artifacts to artifacts folder
           command: |
-            mkdir artifacts
+            [[ ! -d artifacts ]] && { mkdir -p artifacts; }
             find dist -mindepth 1 -maxdepth 1 -type f | xargs -I {} cp {} artifacts
       - run:
           name: Upload artifacts to Bitbucket downloads page when the build is on the master branch
